plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tag:Environment: Development
  instance-state-name: running

compose:
  ansible_host: public_ip_address

keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: tags.Name
    prefix: name
